const DB_NAME='sidestore-web';const DB_VERSION=3;const STORE='apps';const KEY='settings';let selectedFile=null,installPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function allApps(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.id-a.id));r.onerror=()=>rej(r.error)})}
async function putApp(a){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).add(a);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function updateApp(a){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(a);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delApp(id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function settings(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}function saveSettings(v){localStorage.setItem(KEY,JSON.stringify(v))}function base(){return(settings().apiUrl||'').replace(/\/$/,'')}
async function api(path,opt={}){if(!base())throw Error('Configure a signing service in Settings.');const r=await fetch(base()+path,{...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function view(n){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===n));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===n));$('#page-title').textContent={apps:'Apps',add:'Add IPA',devices:'Devices',settings:'Settings'}[n]||'Apps';location.hash=n;if(n==='apps')render();if(n==='devices')devices()}
async function render(){const apps=await allApps();$('#app-count').textContent=apps.length;$('#apps-list').innerHTML=apps.map(a=>`<article class="card"><div class="app-icon">${esc((a.name||'A')[0].toUpperCase())}</div><div class="card-main"><strong>${esc(a.name)}</strong><span>${esc(a.bundleId||'Bundle ID unavailable')} · ${esc(a.version||'Unknown')}</span>${a.status?`<small>${esc(a.status)}</small>`:''}</div><div class="card-actions">${a.installUrl?`<button data-install="${a.id}">Install</button>`:`<button data-sign="${a.id}">${a.status==='signing'?'Signing…':'Sign'}</button>`}<button data-delete="${a.id}" aria-label="Delete">×</button></div></article>`).join('');$('#empty-apps').hidden=apps.length>0;$$('[data-delete]').forEach(b=>b.onclick=async()=>{await delApp(+b.dataset.delete);render();toast('Removed')});$$('[data-sign]').forEach(b=>b.onclick=()=>sign(+b.dataset.sign));$$('[data-install]').forEach(b=>b.onclick=()=>{const a=apps.find(x=>x.id==b.dataset.install);if(a?.installUrl)location.href=a.installUrl})}
async function sign(id){const a=(await allApps()).find(x=>x.id===id);if(!a)return;if(!base()){view('settings');toast('Configure the signing service first');return}try{a.status='signing';await updateApp(a);render();const f=new FormData();f.append('ipa',a.blob,a.filename);f.append('name',a.name);f.append('bundleId',a.bundleId);f.append('version',a.version);const r=await api('/v1/jobs',{method:'POST',body:f});if(r.jobId){a.jobId=r.jobId;await updateApp(a);await poll(r.jobId,id)}else throw Error('Signing service did not return a job ID')}catch(e){a.status='failed';await updateApp(a);render();toast(e.message)}}
async function poll(jobId,id){for(let i=0;i<150;i++){await new Promise(r=>setTimeout(r,2000));try{const r=await api('/v1/jobs/'+encodeURIComponent(jobId));if(r.status==='complete'){const apps=await allApps(),a=apps.find(x=>x.id===id);if(a){a.status='ready';a.installUrl=r.installUrl;a.manifestUrl=r.manifestUrl;await updateApp(a)}toast('Signing complete — Install is ready');render();return}if(r.status==='failed'){const apps=await allApps(),a=apps.find(x=>x.id===id);if(a){a.status='failed';await updateApp(a)}toast(r.error||'Signing failed');render();return}}catch(e){toast(e.message);return}}toast('Signing is still running; reopen the app to check again')}
async function devices(){if(!base())return;try{const d=await api('/v1/devices');const x=d.devices||[];$('#devices-list').innerHTML=x.map(v=>`<article class="card"><div class="app-icon">▣</div><div class="card-main"><strong>${esc(v.name||'Device')}</strong><span>${esc(v.udid||'UDID unavailable')} · ${esc(v.status||'provisioned')}</span></div></article>`).join('');$('#empty-devices').hidden=x.length>0}catch(e){toast(e.message)}}
$('#ipa-file').onchange=e=>{selectedFile=e.target.files?.[0]||null;$('#selected-file').hidden=!selectedFile;$('#selected-file').textContent=selectedFile?`${selectedFile.name} · ${(selectedFile.size/1048576).toFixed(1)} MB`:''};
$('#save-app').onclick=async()=>{if(!selectedFile)return toast('Select an IPA first');const bundle=$('#bundle-id').value.trim();if(!bundle)return toast('Bundle identifier is required');const name=$('#app-name').value.trim()||selectedFile.name.replace(/\.ipa$/i,'');await putApp({name,bundleId:bundle,version:$('#app-version').value.trim()||'1.0',filename:selectedFile.name,size:selectedFile.size,blob:selectedFile,status:'ready-to-sign',createdAt:Date.now()});selectedFile=null;$('#ipa-file').value='';$('#selected-file').hidden=true;['#app-name','#bundle-id','#app-version'].forEach(s=>$(s).value='');toast('IPA saved locally');view('apps')};
$('#save-settings').onclick=()=>{const u=$('#api-url').value.trim();if(u&&!/^https:\/\//i.test(u))return toast('Signing service must use HTTPS');saveSettings({apiUrl:u});toast('Settings saved')};$('#refresh-devices').onclick=devices;$('#clear-local').onclick=async()=>{if(!confirm('Delete all local app data?'))return;const d=await db();d.transaction(STORE,'readwrite').objectStore(STORE).clear();render();toast('Local data cleared')};
$$('[data-tab]').forEach(b=>b.onclick=()=>view(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-pwa').hidden=false});$('#install-pwa').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-pwa').hidden=true}else toast('Safari Share → Add to Home Screen')};window.addEventListener('appinstalled',()=>$('#pwa-status').textContent='Installed as a web app');$('#api-url').value=settings().apiUrl||'';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});view(['apps','add','devices','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'apps');